name: 3D_draw

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: profile-3d-contrib
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: draw
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: commit_changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.repository_owner }}
          author_email: ${{secrets.EMAIL}}
          message: "Create github-profile-3d-contrib by Github Actions"
